"""Import and export reports (guidelines XFER-13): a human-readable account of what a conversion
imported, degraded, dropped, or left dangling, written beside the result."""
from __future__ import annotations

import datetime as dt
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable, Optional

from . import __version__

CATEGORY_TITLES = {
    "dangling": "Links left dangling",
    "degraded": "Constructs degraded",
    "dropped": "Not carried over",
    "unknown-metadata": "Metadata preserved but not understood",
    "attachments": "Attachments",
    "renamed": "Pages renamed",
    "skipped": "Skipped",
    "warning": "Warnings",
    "info": "Notes",
}
_PATTERNS = [
    (re.compile(r"dangling link|not found among|missing concept|unresolved .* block reference"), "dangling"),
    (re.compile(r"degraded|removed|kept as text|collapsed"), "degraded"),
    (re.compile(r"not imported|not exported|dropped|no history exported|cannot"), "dropped"),
    (re.compile(r"reference to .* not found|attachment"), "attachments"),
    (re.compile(r"renamed|reserved"), "renamed"),
    (re.compile(r"skipped|ignored"), "skipped"),
    (re.compile(r"unknown|unrecognized|preserved"), "unknown-metadata"),
]


def categorize(note: str) -> str:
    for pattern, cat in _PATTERNS:
        if pattern.search(note):
            return cat
    return "info"


def _collapse(notes: Iterable[str]) -> list[tuple[str, int]]:
    counts = Counter(notes)
    return sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))


def render_report(*, title: str, source: str, destination: str, direction: str, summary: dict,
                  notes: Iterable[str], fidelity: Optional[dict] = None, extra_sections: Optional[dict] = None,
                  frontmatter: Optional[dict] = None) -> str:
    """Render a Markdown report. `direction` is "import" or "export". `frontmatter`, when given, is
    written as a YAML block first (used to make a report an OKF-conformant concept)."""
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    lines = []
    if frontmatter:
        import yaml  # type: ignore
        fm = dict(frontmatter)
        fm.setdefault("generated", {"by": f"wiki-commons-tools/{__version__}", "at": now})
        lines += ["---", yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).rstrip("\n"), "---", ""]
    lines += [f"# {title}", "", f"Generated by wiki-commons-tools {__version__} on {now}.", ""]
    lines += [f"- **Source:** `{source}`", f"- **Destination:** `{destination}`", f"- **Direction:** {direction}", ""]
    lines += ["## Summary", "", "| What | Count |", "|---|---|"]
    for k, v in summary.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")
    if fidelity:
        lines += ["## Fidelity", "", f"- **Level reached:** {fidelity.get('level', 'n/a')} (0 text, 1 structure, 2 metadata, 3 history, 4 conversation, 5 structured data)"]
        for kind in ("degraded", "dropped"):
            items = fidelity.get(kind) or []
            if items:
                lines.append(f"- **{kind.capitalize()}:**")
                for it in items:
                    count = f" ({it['count']}×)" if it.get("count") else ""
                    how = f": {it['how']}" if it.get("how") else ""
                    lines.append(f"  - {it.get('construct', '?')}{count}{how}")
        lines.append("")
    grouped: dict[str, list[str]] = defaultdict(list)
    for n in notes:
        grouped[categorize(n)].append(n)
    if grouped:
        lines += ["## Details", ""]
        for cat in CATEGORY_TITLES:
            if cat not in grouped:
                continue
            lines.append(f"### {CATEGORY_TITLES[cat]} ({len(grouped[cat])})")
            lines.append("")
            for note, count in _collapse(grouped[cat])[:200]:
                lines.append(f"- {note}" + (f" (×{count})" if count > 1 else ""))
            if len(_collapse(grouped[cat])) > 200:
                lines.append(f"- … and {len(_collapse(grouped[cat])) - 200} more")
            lines.append("")
    else:
        lines += ["## Details", "", "Nothing was degraded or dropped; every construct and link was carried over.", ""]
    for heading, body in (extra_sections or {}).items():
        lines += [f"## {heading}", "", body.rstrip("\n"), ""]
    lines += ["## What to check", "",
              "- Open a few imported pages and compare them with the source; conversions are lossy where listed above.",
              "- Links marked dangling pointed at pages that did not exist in the source either, or at pages whose titles changed; aliases on the target page fix the second kind ([NAV-8](https://kos-commons.github.io/wiki-commons/guidelines/04-Discovery_Navigation_and_Topology.html#nav-8--redirects-and-aliases)).",
              "- Metadata keys that were preserved but not understood are kept verbatim so that a later export loses nothing ([META-11](https://kos-commons.github.io/wiki-commons/guidelines/09-Metadata_and_Frontmatter.html#meta-11--preserve-what-you-do-not-understand)).",
              "- This report is the importer's half of \"declare what you drop\" ([XFER-13](https://kos-commons.github.io/wiki-commons/guidelines/10-Interchange_and_Portability.html#xfer-13--produce-an-import-report)).", ""]
    return "\n".join(lines)


def write_report(path: Path, **kwargs) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(**kwargs), encoding="utf-8")
    return path
